// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebJournal2.Core.Contexts;

namespace WebJournal2.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201028213100_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("WebJournal2.Core.Models.JournalUser", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("CredentialsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebJournal2.Core.Models.UserCredentials", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("WebJournal2.Core.Models.JournalUser", b =>
                {
                    b.HasOne("WebJournal2.Core.Models.UserCredentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId");
                });
#pragma warning restore 612, 618
        }
    }
}
